//! Error codes (`ERR_AUBE_*`).
//!
//! Each constant's *value* matches its identifier. The `ALL` array is
//! the registry — it gates the doc page (`docs/codes.md`) and the
//! self-tests in `lib.rs`. New codes go in both places.

// ── lockfile ─────────────────────────────────────────────────────────
pub const ERR_AUBE_NO_LOCKFILE: &str = "ERR_AUBE_NO_LOCKFILE";
pub const ERR_AUBE_LOCKFILE_PARSE: &str = "ERR_AUBE_LOCKFILE_PARSE";
pub const ERR_AUBE_LOCKFILE_UNSUPPORTED_FORMAT: &str = "ERR_AUBE_LOCKFILE_UNSUPPORTED_FORMAT";

// ── resolver ─────────────────────────────────────────────────────────
pub const ERR_AUBE_NO_MATCHING_VERSION: &str = "ERR_AUBE_NO_MATCHING_VERSION";
pub const ERR_AUBE_NO_MATURE_MATCHING_VERSION: &str = "ERR_AUBE_NO_MATURE_MATCHING_VERSION";
pub const ERR_AUBE_REGISTRY_ERROR: &str = "ERR_AUBE_REGISTRY_ERROR";
pub const ERR_AUBE_UNKNOWN_CATALOG: &str = "ERR_AUBE_UNKNOWN_CATALOG";
pub const ERR_AUBE_UNKNOWN_CATALOG_ENTRY: &str = "ERR_AUBE_UNKNOWN_CATALOG_ENTRY";
pub const ERR_AUBE_BLOCKED_EXOTIC_SUBDEP: &str = "ERR_AUBE_BLOCKED_EXOTIC_SUBDEP";
pub const ERR_AUBE_TRUST_DOWNGRADE: &str = "ERR_AUBE_TRUST_DOWNGRADE";
pub const ERR_AUBE_TRUST_MISSING_TIME: &str = "ERR_AUBE_TRUST_MISSING_TIME";
pub const ERR_AUBE_TRUST_EXCLUDE_INVALID_VERSION_UNION: &str =
    "ERR_AUBE_TRUST_EXCLUDE_INVALID_VERSION_UNION";
pub const ERR_AUBE_TRUST_EXCLUDE_NAME_GLOB_WITH_VERSIONS: &str =
    "ERR_AUBE_TRUST_EXCLUDE_NAME_GLOB_WITH_VERSIONS";
pub const ERR_AUBE_PEER_CONTEXT_NOT_CONVERGED: &str = "ERR_AUBE_PEER_CONTEXT_NOT_CONVERGED";

// ── registry / network ──────────────────────────────────────────────
pub const ERR_AUBE_PACKAGE_NOT_FOUND: &str = "ERR_AUBE_PACKAGE_NOT_FOUND";
pub const ERR_AUBE_VERSION_NOT_FOUND: &str = "ERR_AUBE_VERSION_NOT_FOUND";
pub const ERR_AUBE_UNAUTHORIZED: &str = "ERR_AUBE_UNAUTHORIZED";
pub const ERR_AUBE_OFFLINE: &str = "ERR_AUBE_OFFLINE";
pub const ERR_AUBE_INVALID_PACKAGE_NAME: &str = "ERR_AUBE_INVALID_PACKAGE_NAME";
pub const ERR_AUBE_REGISTRY_WRITE_REJECTED: &str = "ERR_AUBE_REGISTRY_WRITE_REJECTED";

// ── tarball / store ─────────────────────────────────────────────────
pub const ERR_AUBE_TARBALL_INTEGRITY: &str = "ERR_AUBE_TARBALL_INTEGRITY";
pub const ERR_AUBE_TARBALL_EXTRACT: &str = "ERR_AUBE_TARBALL_EXTRACT";
pub const ERR_AUBE_PKG_CONTENT_MISMATCH: &str = "ERR_AUBE_PKG_CONTENT_MISMATCH";
pub const ERR_AUBE_NO_HOME: &str = "ERR_AUBE_NO_HOME";
pub const ERR_AUBE_GIT_ERROR: &str = "ERR_AUBE_GIT_ERROR";

// ── linker ──────────────────────────────────────────────────────────
pub const ERR_AUBE_LINK_FAILED: &str = "ERR_AUBE_LINK_FAILED";
pub const ERR_AUBE_PATCH_FAILED: &str = "ERR_AUBE_PATCH_FAILED";
pub const ERR_AUBE_MISSING_PACKAGE_INDEX: &str = "ERR_AUBE_MISSING_PACKAGE_INDEX";
pub const ERR_AUBE_UNSAFE_INDEX_KEY: &str = "ERR_AUBE_UNSAFE_INDEX_KEY";
pub const ERR_AUBE_MISSING_STORE_FILE: &str = "ERR_AUBE_MISSING_STORE_FILE";

// ── scripts ─────────────────────────────────────────────────────────
pub const ERR_AUBE_SCRIPT_SPAWN: &str = "ERR_AUBE_SCRIPT_SPAWN";
pub const ERR_AUBE_SCRIPT_NON_ZERO_EXIT: &str = "ERR_AUBE_SCRIPT_NON_ZERO_EXIT";
pub const ERR_AUBE_BUILD_POLICY_UNSUPPORTED_VALUE: &str = "ERR_AUBE_BUILD_POLICY_UNSUPPORTED_VALUE";
pub const ERR_AUBE_BUILD_POLICY_INVALID_VERSION_UNION: &str =
    "ERR_AUBE_BUILD_POLICY_INVALID_VERSION_UNION";
pub const ERR_AUBE_BUILD_POLICY_WILDCARD_WITH_VERSION: &str =
    "ERR_AUBE_BUILD_POLICY_WILDCARD_WITH_VERSION";

// ── workspace / filter ──────────────────────────────────────────────
pub const ERR_AUBE_WORKSPACE_PARSE: &str = "ERR_AUBE_WORKSPACE_PARSE";
pub const ERR_AUBE_FILTER_EMPTY: &str = "ERR_AUBE_FILTER_EMPTY";
pub const ERR_AUBE_FILTER_GIT_IO: &str = "ERR_AUBE_FILTER_GIT_IO";
pub const ERR_AUBE_FILTER_GIT_FAILED: &str = "ERR_AUBE_FILTER_GIT_FAILED";

// ── manifest ────────────────────────────────────────────────────────
pub const ERR_AUBE_MANIFEST_PARSE: &str = "ERR_AUBE_MANIFEST_PARSE";
pub const ERR_AUBE_MANIFEST_YAML_PARSE: &str = "ERR_AUBE_MANIFEST_YAML_PARSE";

// ── engine / cli ────────────────────────────────────────────────────
pub const ERR_AUBE_UNSUPPORTED_ENGINE: &str = "ERR_AUBE_UNSUPPORTED_ENGINE";
pub const ERR_AUBE_RECURSIVE_NOT_SUPPORTED: &str = "ERR_AUBE_RECURSIVE_NOT_SUPPORTED";
pub const ERR_AUBE_UNKNOWN_COMMAND: &str = "ERR_AUBE_UNKNOWN_COMMAND";
pub const ERR_AUBE_NPM_ONLY_COMMAND: &str = "ERR_AUBE_NPM_ONLY_COMMAND";
pub const ERR_AUBE_COMPLETION_FAILED: &str = "ERR_AUBE_COMPLETION_FAILED";
pub const ERR_AUBE_REMOVE_PRIOR_INSTALL_DIR: &str = "ERR_AUBE_REMOVE_PRIOR_INSTALL_DIR";

// ── misc tracing::error! sites (non-fatal but high-severity) ────────
pub const ERR_AUBE_PATCHES_TRACKING_WRITE: &str = "ERR_AUBE_PATCHES_TRACKING_WRITE";
pub const ERR_AUBE_UNSAFE_SHEBANG_INTERPRETER: &str = "ERR_AUBE_UNSAFE_SHEBANG_INTERPRETER";

/// Registry of every error code, used by self-tests and the docs
/// generator. Pairs (name, value) — the const name on the left, the
/// emitted string on the right. They must match.
pub const ALL: &[(&str, &str)] = &[
    ("ERR_AUBE_NO_LOCKFILE", ERR_AUBE_NO_LOCKFILE),
    ("ERR_AUBE_LOCKFILE_PARSE", ERR_AUBE_LOCKFILE_PARSE),
    (
        "ERR_AUBE_LOCKFILE_UNSUPPORTED_FORMAT",
        ERR_AUBE_LOCKFILE_UNSUPPORTED_FORMAT,
    ),
    ("ERR_AUBE_NO_MATCHING_VERSION", ERR_AUBE_NO_MATCHING_VERSION),
    (
        "ERR_AUBE_NO_MATURE_MATCHING_VERSION",
        ERR_AUBE_NO_MATURE_MATCHING_VERSION,
    ),
    ("ERR_AUBE_REGISTRY_ERROR", ERR_AUBE_REGISTRY_ERROR),
    ("ERR_AUBE_UNKNOWN_CATALOG", ERR_AUBE_UNKNOWN_CATALOG),
    (
        "ERR_AUBE_UNKNOWN_CATALOG_ENTRY",
        ERR_AUBE_UNKNOWN_CATALOG_ENTRY,
    ),
    (
        "ERR_AUBE_BLOCKED_EXOTIC_SUBDEP",
        ERR_AUBE_BLOCKED_EXOTIC_SUBDEP,
    ),
    ("ERR_AUBE_TRUST_DOWNGRADE", ERR_AUBE_TRUST_DOWNGRADE),
    ("ERR_AUBE_TRUST_MISSING_TIME", ERR_AUBE_TRUST_MISSING_TIME),
    (
        "ERR_AUBE_TRUST_EXCLUDE_INVALID_VERSION_UNION",
        ERR_AUBE_TRUST_EXCLUDE_INVALID_VERSION_UNION,
    ),
    (
        "ERR_AUBE_TRUST_EXCLUDE_NAME_GLOB_WITH_VERSIONS",
        ERR_AUBE_TRUST_EXCLUDE_NAME_GLOB_WITH_VERSIONS,
    ),
    (
        "ERR_AUBE_PEER_CONTEXT_NOT_CONVERGED",
        ERR_AUBE_PEER_CONTEXT_NOT_CONVERGED,
    ),
    ("ERR_AUBE_PACKAGE_NOT_FOUND", ERR_AUBE_PACKAGE_NOT_FOUND),
    ("ERR_AUBE_VERSION_NOT_FOUND", ERR_AUBE_VERSION_NOT_FOUND),
    ("ERR_AUBE_UNAUTHORIZED", ERR_AUBE_UNAUTHORIZED),
    ("ERR_AUBE_OFFLINE", ERR_AUBE_OFFLINE),
    (
        "ERR_AUBE_INVALID_PACKAGE_NAME",
        ERR_AUBE_INVALID_PACKAGE_NAME,
    ),
    (
        "ERR_AUBE_REGISTRY_WRITE_REJECTED",
        ERR_AUBE_REGISTRY_WRITE_REJECTED,
    ),
    ("ERR_AUBE_TARBALL_INTEGRITY", ERR_AUBE_TARBALL_INTEGRITY),
    ("ERR_AUBE_TARBALL_EXTRACT", ERR_AUBE_TARBALL_EXTRACT),
    (
        "ERR_AUBE_PKG_CONTENT_MISMATCH",
        ERR_AUBE_PKG_CONTENT_MISMATCH,
    ),
    ("ERR_AUBE_NO_HOME", ERR_AUBE_NO_HOME),
    ("ERR_AUBE_GIT_ERROR", ERR_AUBE_GIT_ERROR),
    ("ERR_AUBE_LINK_FAILED", ERR_AUBE_LINK_FAILED),
    ("ERR_AUBE_PATCH_FAILED", ERR_AUBE_PATCH_FAILED),
    (
        "ERR_AUBE_MISSING_PACKAGE_INDEX",
        ERR_AUBE_MISSING_PACKAGE_INDEX,
    ),
    ("ERR_AUBE_UNSAFE_INDEX_KEY", ERR_AUBE_UNSAFE_INDEX_KEY),
    ("ERR_AUBE_MISSING_STORE_FILE", ERR_AUBE_MISSING_STORE_FILE),
    ("ERR_AUBE_SCRIPT_SPAWN", ERR_AUBE_SCRIPT_SPAWN),
    (
        "ERR_AUBE_SCRIPT_NON_ZERO_EXIT",
        ERR_AUBE_SCRIPT_NON_ZERO_EXIT,
    ),
    (
        "ERR_AUBE_BUILD_POLICY_UNSUPPORTED_VALUE",
        ERR_AUBE_BUILD_POLICY_UNSUPPORTED_VALUE,
    ),
    (
        "ERR_AUBE_BUILD_POLICY_INVALID_VERSION_UNION",
        ERR_AUBE_BUILD_POLICY_INVALID_VERSION_UNION,
    ),
    (
        "ERR_AUBE_BUILD_POLICY_WILDCARD_WITH_VERSION",
        ERR_AUBE_BUILD_POLICY_WILDCARD_WITH_VERSION,
    ),
    ("ERR_AUBE_WORKSPACE_PARSE", ERR_AUBE_WORKSPACE_PARSE),
    ("ERR_AUBE_FILTER_EMPTY", ERR_AUBE_FILTER_EMPTY),
    ("ERR_AUBE_FILTER_GIT_IO", ERR_AUBE_FILTER_GIT_IO),
    ("ERR_AUBE_FILTER_GIT_FAILED", ERR_AUBE_FILTER_GIT_FAILED),
    ("ERR_AUBE_MANIFEST_PARSE", ERR_AUBE_MANIFEST_PARSE),
    ("ERR_AUBE_MANIFEST_YAML_PARSE", ERR_AUBE_MANIFEST_YAML_PARSE),
    ("ERR_AUBE_UNSUPPORTED_ENGINE", ERR_AUBE_UNSUPPORTED_ENGINE),
    (
        "ERR_AUBE_RECURSIVE_NOT_SUPPORTED",
        ERR_AUBE_RECURSIVE_NOT_SUPPORTED,
    ),
    ("ERR_AUBE_UNKNOWN_COMMAND", ERR_AUBE_UNKNOWN_COMMAND),
    ("ERR_AUBE_NPM_ONLY_COMMAND", ERR_AUBE_NPM_ONLY_COMMAND),
    ("ERR_AUBE_COMPLETION_FAILED", ERR_AUBE_COMPLETION_FAILED),
    (
        "ERR_AUBE_REMOVE_PRIOR_INSTALL_DIR",
        ERR_AUBE_REMOVE_PRIOR_INSTALL_DIR,
    ),
    (
        "ERR_AUBE_PATCHES_TRACKING_WRITE",
        ERR_AUBE_PATCHES_TRACKING_WRITE,
    ),
    (
        "ERR_AUBE_UNSAFE_SHEBANG_INTERPRETER",
        ERR_AUBE_UNSAFE_SHEBANG_INTERPRETER,
    ),
];
