//! Warning codes (`WARN_AUBE_*`).
//!
//! Same shape as `errors`: each constant value matches its identifier;
//! `ALL` is the registry consumed by self-tests and the docs page.

// ── pnpmfile / hooks ────────────────────────────────────────────────
pub const WARN_AUBE_PNPMFILE_NOT_FOUND: &str = "WARN_AUBE_PNPMFILE_NOT_FOUND";
pub const WARN_AUBE_PNPMFILE_STDERR_FORWARDER: &str = "WARN_AUBE_PNPMFILE_STDERR_FORWARDER";
pub const WARN_AUBE_HOOK_IMPORTER_MUTATED: &str = "WARN_AUBE_HOOK_IMPORTER_MUTATED";
pub const WARN_AUBE_HOOK_IMPORTER_ADDED: &str = "WARN_AUBE_HOOK_IMPORTER_ADDED";
pub const WARN_AUBE_HOOK_IDENTITY_REWRITTEN: &str = "WARN_AUBE_HOOK_IDENTITY_REWRITTEN";
pub const WARN_AUBE_HOOK_PACKAGE_ADDED: &str = "WARN_AUBE_HOOK_PACKAGE_ADDED";

// ── install lifecycle ───────────────────────────────────────────────
pub const WARN_AUBE_IGNORED_BUILD_SCRIPTS: &str = "WARN_AUBE_IGNORED_BUILD_SCRIPTS";
pub const WARN_AUBE_MISSING_INTEGRITY: &str = "WARN_AUBE_MISSING_INTEGRITY";
pub const WARN_AUBE_CACHE_WRITE_FAILED: &str = "WARN_AUBE_CACHE_WRITE_FAILED";
pub const WARN_AUBE_CLONE_STRATEGY_FALLBACK: &str = "WARN_AUBE_CLONE_STRATEGY_FALLBACK";
pub const WARN_AUBE_LTHASH_MISMATCH: &str = "WARN_AUBE_LTHASH_MISMATCH";
pub const WARN_AUBE_DELTA_INVALIDATE_FAILED: &str = "WARN_AUBE_DELTA_INVALIDATE_FAILED";
pub const WARN_AUBE_GVS_INCOMPATIBLE: &str = "WARN_AUBE_GVS_INCOMPATIBLE";
pub const WARN_AUBE_GVS_MODE_CHANGED: &str = "WARN_AUBE_GVS_MODE_CHANGED";

// ── settings / config validation ────────────────────────────────────
pub const WARN_AUBE_INVALID_CONCURRENCY: &str = "WARN_AUBE_INVALID_CONCURRENCY";
pub const WARN_AUBE_INVALID_TRUST_POLICY: &str = "WARN_AUBE_INVALID_TRUST_POLICY";
pub const WARN_AUBE_OVERRIDE_MISSING_DEP: &str = "WARN_AUBE_OVERRIDE_MISSING_DEP";
pub const WARN_AUBE_INVALID_PEER_PATTERN: &str = "WARN_AUBE_INVALID_PEER_PATTERN";
pub const WARN_AUBE_INVALID_SAVE_PREFIX: &str = "WARN_AUBE_INVALID_SAVE_PREFIX";
pub const WARN_AUBE_CONCURRENCY_ENV_INVALID: &str = "WARN_AUBE_CONCURRENCY_ENV_INVALID";

// ── update / prerelease ─────────────────────────────────────────────
pub const WARN_AUBE_PRERELEASE_CHECK_SKIPPED: &str = "WARN_AUBE_PRERELEASE_CHECK_SKIPPED";

// ── audit / npmrc ───────────────────────────────────────────────────
pub const WARN_AUBE_AUDIT_FETCH_FAILED: &str = "WARN_AUBE_AUDIT_FETCH_FAILED";
pub const WARN_AUBE_TOKEN_CHMOD_FAILED: &str = "WARN_AUBE_TOKEN_CHMOD_FAILED";

// ── registry config (trust gates + validation) ──────────────────────
pub const WARN_AUBE_UNTRUSTED_PROXY: &str = "WARN_AUBE_UNTRUSTED_PROXY";
pub const WARN_AUBE_UNTRUSTED_STRICT_SSL_DISABLE: &str = "WARN_AUBE_UNTRUSTED_STRICT_SSL_DISABLE";
pub const WARN_AUBE_INVALID_LOCAL_ADDRESS: &str = "WARN_AUBE_INVALID_LOCAL_ADDRESS";
pub const WARN_AUBE_INVALID_MAXSOCKETS: &str = "WARN_AUBE_INVALID_MAXSOCKETS";
pub const WARN_AUBE_UNTRUSTED_TOKEN_HELPER: &str = "WARN_AUBE_UNTRUSTED_TOKEN_HELPER";
pub const WARN_AUBE_INVALID_TOKEN_HELPER: &str = "WARN_AUBE_INVALID_TOKEN_HELPER";
pub const WARN_AUBE_TOKEN_HELPER_SPAWN_FAILED: &str = "WARN_AUBE_TOKEN_HELPER_SPAWN_FAILED";
pub const WARN_AUBE_TOKEN_HELPER_NON_ZERO_EXIT: &str = "WARN_AUBE_TOKEN_HELPER_NON_ZERO_EXIT";

// ── registry HTTP retries ───────────────────────────────────────────
pub const WARN_AUBE_HTTP_RETRY_TRANSIENT: &str = "WARN_AUBE_HTTP_RETRY_TRANSIENT";
pub const WARN_AUBE_HTTP_RETRY_TRANSPORT: &str = "WARN_AUBE_HTTP_RETRY_TRANSPORT";
pub const WARN_AUBE_HTTP_RETRY_BODY_READ: &str = "WARN_AUBE_HTTP_RETRY_BODY_READ";
pub const WARN_AUBE_HTTP_RETRY_BODY_DECODE: &str = "WARN_AUBE_HTTP_RETRY_BODY_DECODE";

// ── registry caching / perf ─────────────────────────────────────────
pub const WARN_AUBE_PACKUMENT_CACHE_WRITE: &str = "WARN_AUBE_PACKUMENT_CACHE_WRITE";
pub const WARN_AUBE_SLOW_METADATA: &str = "WARN_AUBE_SLOW_METADATA";
pub const WARN_AUBE_SLOW_TARBALL: &str = "WARN_AUBE_SLOW_TARBALL";

// ── registry TLS / proxy config ─────────────────────────────────────
pub const WARN_AUBE_INVALID_HTTPS_PROXY: &str = "WARN_AUBE_INVALID_HTTPS_PROXY";
pub const WARN_AUBE_INVALID_HTTP_PROXY: &str = "WARN_AUBE_INVALID_HTTP_PROXY";
pub const WARN_AUBE_INVALID_CA: &str = "WARN_AUBE_INVALID_CA";
pub const WARN_AUBE_INVALID_CAFILE: &str = "WARN_AUBE_INVALID_CAFILE";
pub const WARN_AUBE_UNREADABLE_CAFILE: &str = "WARN_AUBE_UNREADABLE_CAFILE";
pub const WARN_AUBE_INVALID_CLIENT_CERT: &str = "WARN_AUBE_INVALID_CLIENT_CERT";

// ── resolver ────────────────────────────────────────────────────────
pub const WARN_AUBE_UNSUPPORTED_PLATFORM_INSTALL: &str = "WARN_AUBE_UNSUPPORTED_PLATFORM_INSTALL";
pub const WARN_AUBE_EXOTIC_SUBDEP_SKIPPED: &str = "WARN_AUBE_EXOTIC_SUBDEP_SKIPPED";
pub const WARN_AUBE_PEER_DEDUPE_COLLISION: &str = "WARN_AUBE_PEER_DEDUPE_COLLISION";

// ── lockfile ────────────────────────────────────────────────────────
pub const WARN_AUBE_LOCKFILE_MERGE_CONFLICT: &str = "WARN_AUBE_LOCKFILE_MERGE_CONFLICT";
pub const WARN_AUBE_LOCKFILE_MERGE_CLEANUP_FAILED: &str = "WARN_AUBE_LOCKFILE_MERGE_CLEANUP_FAILED";
pub const WARN_AUBE_YARN_BERRY_UNSUPPORTED: &str = "WARN_AUBE_YARN_BERRY_UNSUPPORTED";

/// Registry of every warning code, used by self-tests and the docs
/// generator. New codes must be added here.
pub const ALL: &[(&str, &str)] = &[
    ("WARN_AUBE_PNPMFILE_NOT_FOUND", WARN_AUBE_PNPMFILE_NOT_FOUND),
    (
        "WARN_AUBE_PNPMFILE_STDERR_FORWARDER",
        WARN_AUBE_PNPMFILE_STDERR_FORWARDER,
    ),
    (
        "WARN_AUBE_HOOK_IMPORTER_MUTATED",
        WARN_AUBE_HOOK_IMPORTER_MUTATED,
    ),
    (
        "WARN_AUBE_HOOK_IMPORTER_ADDED",
        WARN_AUBE_HOOK_IMPORTER_ADDED,
    ),
    (
        "WARN_AUBE_HOOK_IDENTITY_REWRITTEN",
        WARN_AUBE_HOOK_IDENTITY_REWRITTEN,
    ),
    ("WARN_AUBE_HOOK_PACKAGE_ADDED", WARN_AUBE_HOOK_PACKAGE_ADDED),
    (
        "WARN_AUBE_IGNORED_BUILD_SCRIPTS",
        WARN_AUBE_IGNORED_BUILD_SCRIPTS,
    ),
    ("WARN_AUBE_MISSING_INTEGRITY", WARN_AUBE_MISSING_INTEGRITY),
    ("WARN_AUBE_CACHE_WRITE_FAILED", WARN_AUBE_CACHE_WRITE_FAILED),
    (
        "WARN_AUBE_CLONE_STRATEGY_FALLBACK",
        WARN_AUBE_CLONE_STRATEGY_FALLBACK,
    ),
    ("WARN_AUBE_LTHASH_MISMATCH", WARN_AUBE_LTHASH_MISMATCH),
    (
        "WARN_AUBE_DELTA_INVALIDATE_FAILED",
        WARN_AUBE_DELTA_INVALIDATE_FAILED,
    ),
    ("WARN_AUBE_GVS_INCOMPATIBLE", WARN_AUBE_GVS_INCOMPATIBLE),
    ("WARN_AUBE_GVS_MODE_CHANGED", WARN_AUBE_GVS_MODE_CHANGED),
    (
        "WARN_AUBE_INVALID_CONCURRENCY",
        WARN_AUBE_INVALID_CONCURRENCY,
    ),
    (
        "WARN_AUBE_INVALID_TRUST_POLICY",
        WARN_AUBE_INVALID_TRUST_POLICY,
    ),
    (
        "WARN_AUBE_OVERRIDE_MISSING_DEP",
        WARN_AUBE_OVERRIDE_MISSING_DEP,
    ),
    (
        "WARN_AUBE_INVALID_PEER_PATTERN",
        WARN_AUBE_INVALID_PEER_PATTERN,
    ),
    (
        "WARN_AUBE_INVALID_SAVE_PREFIX",
        WARN_AUBE_INVALID_SAVE_PREFIX,
    ),
    (
        "WARN_AUBE_CONCURRENCY_ENV_INVALID",
        WARN_AUBE_CONCURRENCY_ENV_INVALID,
    ),
    (
        "WARN_AUBE_PRERELEASE_CHECK_SKIPPED",
        WARN_AUBE_PRERELEASE_CHECK_SKIPPED,
    ),
    ("WARN_AUBE_AUDIT_FETCH_FAILED", WARN_AUBE_AUDIT_FETCH_FAILED),
    ("WARN_AUBE_TOKEN_CHMOD_FAILED", WARN_AUBE_TOKEN_CHMOD_FAILED),
    ("WARN_AUBE_UNTRUSTED_PROXY", WARN_AUBE_UNTRUSTED_PROXY),
    (
        "WARN_AUBE_UNTRUSTED_STRICT_SSL_DISABLE",
        WARN_AUBE_UNTRUSTED_STRICT_SSL_DISABLE,
    ),
    (
        "WARN_AUBE_INVALID_LOCAL_ADDRESS",
        WARN_AUBE_INVALID_LOCAL_ADDRESS,
    ),
    ("WARN_AUBE_INVALID_MAXSOCKETS", WARN_AUBE_INVALID_MAXSOCKETS),
    (
        "WARN_AUBE_UNTRUSTED_TOKEN_HELPER",
        WARN_AUBE_UNTRUSTED_TOKEN_HELPER,
    ),
    (
        "WARN_AUBE_INVALID_TOKEN_HELPER",
        WARN_AUBE_INVALID_TOKEN_HELPER,
    ),
    (
        "WARN_AUBE_TOKEN_HELPER_SPAWN_FAILED",
        WARN_AUBE_TOKEN_HELPER_SPAWN_FAILED,
    ),
    (
        "WARN_AUBE_TOKEN_HELPER_NON_ZERO_EXIT",
        WARN_AUBE_TOKEN_HELPER_NON_ZERO_EXIT,
    ),
    (
        "WARN_AUBE_HTTP_RETRY_TRANSIENT",
        WARN_AUBE_HTTP_RETRY_TRANSIENT,
    ),
    (
        "WARN_AUBE_HTTP_RETRY_TRANSPORT",
        WARN_AUBE_HTTP_RETRY_TRANSPORT,
    ),
    (
        "WARN_AUBE_HTTP_RETRY_BODY_READ",
        WARN_AUBE_HTTP_RETRY_BODY_READ,
    ),
    (
        "WARN_AUBE_HTTP_RETRY_BODY_DECODE",
        WARN_AUBE_HTTP_RETRY_BODY_DECODE,
    ),
    (
        "WARN_AUBE_PACKUMENT_CACHE_WRITE",
        WARN_AUBE_PACKUMENT_CACHE_WRITE,
    ),
    ("WARN_AUBE_SLOW_METADATA", WARN_AUBE_SLOW_METADATA),
    ("WARN_AUBE_SLOW_TARBALL", WARN_AUBE_SLOW_TARBALL),
    (
        "WARN_AUBE_INVALID_HTTPS_PROXY",
        WARN_AUBE_INVALID_HTTPS_PROXY,
    ),
    ("WARN_AUBE_INVALID_HTTP_PROXY", WARN_AUBE_INVALID_HTTP_PROXY),
    ("WARN_AUBE_INVALID_CA", WARN_AUBE_INVALID_CA),
    ("WARN_AUBE_INVALID_CAFILE", WARN_AUBE_INVALID_CAFILE),
    ("WARN_AUBE_UNREADABLE_CAFILE", WARN_AUBE_UNREADABLE_CAFILE),
    (
        "WARN_AUBE_INVALID_CLIENT_CERT",
        WARN_AUBE_INVALID_CLIENT_CERT,
    ),
    (
        "WARN_AUBE_UNSUPPORTED_PLATFORM_INSTALL",
        WARN_AUBE_UNSUPPORTED_PLATFORM_INSTALL,
    ),
    (
        "WARN_AUBE_EXOTIC_SUBDEP_SKIPPED",
        WARN_AUBE_EXOTIC_SUBDEP_SKIPPED,
    ),
    (
        "WARN_AUBE_PEER_DEDUPE_COLLISION",
        WARN_AUBE_PEER_DEDUPE_COLLISION,
    ),
    (
        "WARN_AUBE_LOCKFILE_MERGE_CONFLICT",
        WARN_AUBE_LOCKFILE_MERGE_CONFLICT,
    ),
    (
        "WARN_AUBE_LOCKFILE_MERGE_CLEANUP_FAILED",
        WARN_AUBE_LOCKFILE_MERGE_CLEANUP_FAILED,
    ),
    (
        "WARN_AUBE_YARN_BERRY_UNSUPPORTED",
        WARN_AUBE_YARN_BERRY_UNSUPPORTED,
    ),
];
